name: flutter_login
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.3.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/Burger.png
  branding: assets/images/Burger.png
  color_dark: "#121212"
  image_dark: assets/images/Burger.png
  branding_dark: assets/images/Burger.png

  android_12:
    image: assets/images/Burger.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/Burger.png
    icon_background_color_dark: "#121212"



assets:
  - assets/images/





flutter:

  
  
  
  uses-material-design: true

  
  
